-- -- Split: generated bucket wallets (Step 4) --------------------------------
-- A wallet-bucket can now have its destination generated by the app rather than
-- pasted by the user. The key is derived from a wallet signature plus a
-- derivation index (lib/bucket-wallet.ts), so nothing secret is stored here.
--
-- This table is a HINT, never an authority. It exists so badges and the Total
-- Balance breakdown can render without demanding a signature. Spending always
-- re-derives the key and asserts the derived address matches the bucket's
-- on-chain destination before moving anything, so a wrong or missing row can
-- never cause funds to be sent to the wrong place - only a degraded display.
--
-- Losing this table entirely is survivable: recoverBucketWalletIndices() rebuilds
-- the mapping by scanning derivation indices against on-chain destinations.
--
-- Run once:  Dashboard -> SQL Editor -> paste and execute  (or `supabase db push`)

create table if not exists bucket_wallets (
  id               uuid        default gen_random_uuid() primary key,
  address          text        not null,   -- owner's main address, checksummed
  derivation_index integer     not null,
  wallet_address   text        not null,   -- the derived address, checksummed
  bucket_id        bigint,                 -- null until bound (see below)
  created_at       timestamptz default now(),
  bound_at         timestamptz,

  -- Mirrors MAX_DERIVATION_INDEX in lib/bucket-wallet.ts.
  constraint bucket_wallets_index_range check (derivation_index between 0 and 100000),

  -- THE race-proof backstop. Reserve is an INSERT: when two tabs race for the
  -- same index, Postgres accepts exactly one and rejects the other with 23505
  -- unique_violation, which the caller catches to pick the next free index and
  -- retry. A read-then-write "is this index taken?" check would not do - both
  -- readers see it free before either writes. Same reasoning as
  -- payroll_runs_one_active_idx in migration 002.
  constraint bucket_wallets_index_uniq unique (address, derivation_index)
);

create index if not exists bucket_wallets_address_idx on bucket_wallets (address);

-- One generated wallet per bucket, enforced only once a row is actually bound.
-- Unbound reservations are exempt, so several may sit in flight at once.
--
-- bucket_id has no foreign key on purpose: buckets live on-chain, not in this
-- database, so there is no table to reference. Nor can a stale row block a later
-- bind - Split allocates ids with `nextBucketId[msg.sender]++` and deleteBucket
-- never decrements it, so an id is never reissued. Rows left behind by a deleted
-- bucket are inert: they hold one derivation index that allocation then skips.
create unique index if not exists bucket_wallets_bucket_uniq
  on bucket_wallets (address, bucket_id) where bucket_id is not null;

-- -- Row Level Security ------------------------------------------------------
-- Private per-user data, like the payroll tables. Deny all public access; the
-- server routes use SUPABASE_SERVICE_ROLE_KEY, which bypasses RLS.

alter table bucket_wallets enable row level security;

create policy "bucket_wallets_deny_public" on bucket_wallets as restrictive using (false);
